language: ruby

cache: bundler

sudo: required

dist: trusty

services:
- docker

before_install:
# update core ruby dependencies
- gem update --system
- gem update bundler

script:
- ./.travis.sh

# push gem to rubygems.org
# push cookbook to supermarket
